### ISSUE TITLE
FAIRify

### ISSUE THREAD

**Issue by MartineDeVos** [UtrechtUniversity/anonymouus#1]
Make your software fair by:
* Adding a license, e.g. MIT or Apache 2.0
* Registering your code in a community registry, e.g. Zenodo
* Enabling citation of your software 

Find concrete tips and tricks at the [fair-software website](https://fair-software.nl/)

**Comment by DorienHuijser** [comment]
What still needs to happen is:
- **Add a license**. My guess is that we should use MIT of GPL-3.0
- **Registry**: anonymoUUs is already registered in PyPi right?
-  **Citation**: 
   - Add a cff file to the repo: https://citation-file-format.github.io/cff-initializer-javascript/#/start OR add a .zenodo file, like https://github.com/asreview/asreview/blob/master/.zenodo.json to get the metadata for Zenodo right.
   - When there is a full first release, publish the release on Zenodo: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content
 - In the end, use a software quality checklist: https://fair-software.nl/recommendations/checklist. I have never done this before, but apparently this one seems ok: https://github.com/CLARIAH/software-quality-guidelines/blob/v1.0/softwareguidelines.pdf

**Comment by MartineDeVos** [comment]
I have added MIT license and registered the code in Zenodo.
The code is already registerd at Pypi, but I additionally registerd it at Zenodo to create a DOI. 
This is required to enable citation of the software
